#!/usr/sbin/nft -f

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter;
    policy accept;

    ct state established,related accept
    tcp dport 22 accept
    iifname "wwan0" drop
  }
}
