# SPDX-License-Identifier: GPL-2.0-only
obj-m += spectra_camera.o

ccflags-y += -I$(src) -I$(src)/uapi -include $(src)/spectra_module.h
ccflags-y += -I$(src)/camera/cam_core
ccflags-y += -I$(src)/camera/cam_smmu
ccflags-y += -I$(src)/camera/cam_utils
ccflags-y += -I$(src)/camera/cam_req_mgr
ccflags-y += -I$(src)/camera/cam_sync
ccflags-y += -I$(src)/camera/cam_cpas/include
ccflags-y += -I$(src)/camera/cam_cpas/cpas_top
ccflags-y += -I$(src)/camera/cam_cpas/camss_top
ccflags-y += -I$(src)/camera/cam_cpas
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/include
ccflags-y += -I$(src)/camera/cam_cdm
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/include
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus/include
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/include
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top
ccflags-y += -I$(src)/camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_cci
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_res_mgr
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_eeprom
ccflags-y += -I$(src)/camera/cam_sensor_module/cam_sensor
ccflags-y += -I$(src)/camera/cam_icp
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/include
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -I$(src)/camera/cam_icp/fw_inc
ccflags-y += -I$(src)/camera
ccflags-y += -I$(src)/camera/isp/isp_hw/include
ccflags-y += -I$(src)/camera/isp/isp_hw/hw_utils/include
ccflags-y += -I$(src)/camera/isp/isp_hw/isp_hw_mgr
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/a5_hw
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/ipe_hw
ccflags-y += -I$(src)/camera/cam_icp/icp_hw/bps_hw
ccflags-y += -I$(src)/camera/cam_jpeg/jpeg_hw
ccflags-y += -I$(src)/camera/cam_jpeg/jpeg_hw/include
ccflags-y += -I$(src)/camera/cam_jpeg
ccflags-y += -I$(src)/camera/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -I$(src)/camera/cam_jpeg/jpeg_hw/jpeg_enc_hw
ccflags-y += -I$(src)/camera/cam_jpeg/jpeg_hw/jpeg_dma_hw
ccflags-y += -I$(src)/camera/cam_fd
ccflags-y += -I$(src)/camera/cam_fd/fd_hw_mgr
ccflags-y += -I$(src)/camera/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -I$(src)/camera/cam_lrme
ccflags-y += -I$(src)/camera/cam_lrme/lrme_hw_mgr
ccflags-y += -I$(src)/camera/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(src)/camera0

spectra_camera-y := spectra_module.o \
	camera/cam_req_mgr/cam_req_mgr_core.o \
	camera/cam_req_mgr/cam_req_mgr_dev.o \
	camera/cam_req_mgr/cam_req_mgr_util.o \
	camera/cam_req_mgr/cam_req_mgr_workq.o \
	camera/cam_req_mgr/cam_mem_mgr.o \
	camera/cam_req_mgr/cam_req_mgr_timer.o \
	camera/cam_req_mgr/cam_req_mgr_debug.o \
	camera/cam_utils/cam_soc_util.o \
	camera/cam_utils/cam_io_util.o \
	camera/cam_utils/cam_packet_util.o \
	camera/cam_utils/cam_debug_util.o \
	camera/cam_utils/cam_trace.o \
	camera/cam_utils/cam_common_util.o \
	camera/cam_core/cam_context.o \
	camera/cam_core/cam_context_utils.o \
	camera/cam_core/cam_node.o \
	camera/cam_core/cam_subdev.o \
	camera/cam_sync/cam_sync.o \
	camera/cam_sync/cam_sync_util.o \
	camera/cam_smmu/cam_smmu_api.o \
	camera/cam_cpas/cpas_top/cam_cpastop_hw.o \
	camera/cam_cpas/camss_top/cam_camsstop_hw.o \
	camera/cam_cpas/cam_cpas_soc.o \
	camera/cam_cpas/cam_cpas_intf.o \
	camera/cam_cpas/cam_cpas_hw.o \
	camera/cam_cdm/cam_cdm_soc.o \
	camera/cam_cdm/cam_cdm_util.o \
	camera/cam_cdm/cam_cdm_intf.o \
	camera/cam_cdm/cam_cdm_core_common.o \
	camera/cam_cdm/cam_cdm_virtual_core.o \
	camera/cam_cdm/cam_cdm_hw_core.o \
	camera/cam_isp/isp_hw_mgr/hw_utils/cam_tasklet_util.o \
	camera/cam_isp/isp_hw_mgr/hw_utils/cam_isp_packet_parser.o \
	camera/cam_isp/isp_hw_mgr/hw_utils/irq_controller/cam_irq_controller.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_dev.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_soc.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_core.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid170.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_lite170.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/cam_vfe_soc.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/cam_vfe_dev.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/cam_vfe_core.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus/cam_vfe_bus.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_bus/cam_vfe_bus_ver2.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_top.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_top_ver2.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_camif_ver2.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_rdi.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe170/cam_vfe170.o \
	camera/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe170/cam_vfe_lite170.o \
	camera/cam_isp/isp_hw_mgr/cam_isp_hw_mgr.o \
	camera/cam_isp/isp_hw_mgr/cam_ife_hw_mgr.o \
	camera/cam_isp/cam_isp_dev.o \
	camera/cam_isp/cam_isp_context.o \
	camera/cam_sensor_module/cam_res_mgr/cam_res_mgr.o \
	camera/cam_sensor_module/cam_sensor_utils/cam_sensor_util.o \
	camera/cam_sensor_module/cam_cci/cam_cci_dev.o \
	camera/cam_sensor_module/cam_cci/cam_cci_core.o \
	camera/cam_sensor_module/cam_cci/cam_cci_soc.o \
	camera/cam_sensor_module/cam_sensor_io/cam_sensor_io.o \
	camera/cam_sensor_module/cam_sensor_io/cam_sensor_cci_i2c.o \
	camera/cam_sensor_module/cam_sensor_io/cam_sensor_qup_i2c.o \
	camera/cam_sensor_module/cam_sensor_io/cam_sensor_spi.o \
	camera/cam_sensor_module/cam_csiphy/cam_csiphy_soc.o \
	camera/cam_sensor_module/cam_csiphy/cam_csiphy_dev.o \
	camera/cam_sensor_module/cam_csiphy/cam_csiphy_core.o \
	camera/cam_sensor_module/cam_actuator/cam_actuator_dev.o \
	camera/cam_sensor_module/cam_actuator/cam_actuator_core.o \
	camera/cam_sensor_module/cam_actuator/cam_actuator_soc.o \
	camera/cam_sensor_module/cam_sensor/cam_sensor_dev.o \
	camera/cam_sensor_module/cam_sensor/cam_sensor_core.o \
	camera/cam_sensor_module/cam_sensor/cam_sensor_soc.o \
	camera/cam_sensor_module/cam_flash/cam_flash_dev.o \
	camera/cam_sensor_module/cam_flash/cam_flash_core.o \
	camera/cam_sensor_module/cam_flash/cam_flash_soc.o \
	camera/cam_sensor_module/cam_eeprom/cam_eeprom_dev.o \
	camera/cam_sensor_module/cam_eeprom/cam_eeprom_core.o \
	camera/cam_sensor_module/cam_eeprom/cam_eeprom_soc.o \
	camera/cam_sensor_module/cam_eeprom/cam_eeprom_offload.o \
	camera/cam_sensor_module/cam_eeprom/cam_eeprom_toflist.o \
	camera/cam_sensor_module/cam_ois/cam_ois_dev.o \
	camera/cam_sensor_module/cam_ois/cam_ois_core.o \
	camera/cam_sensor_module/cam_ois/cam_ois_soc.o \
	camera/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.o \
	camera/cam_icp/icp_hw/a5_hw/a5_dev.o \
	camera/cam_icp/icp_hw/a5_hw/a5_core.o \
	camera/cam_icp/icp_hw/a5_hw/a5_soc.o \
	camera/cam_icp/icp_hw/ipe_hw/ipe_dev.o \
	camera/cam_icp/icp_hw/ipe_hw/ipe_core.o \
	camera/cam_icp/icp_hw/ipe_hw/ipe_soc.o \
	camera/cam_icp/icp_hw/bps_hw/bps_dev.o \
	camera/cam_icp/icp_hw/bps_hw/bps_core.o \
	camera/cam_icp/icp_hw/bps_hw/bps_soc.o \
	camera/cam_icp/cam_icp_subdev.o \
	camera/cam_icp/cam_icp_context.o \
	camera/cam_icp/hfi.o \
	camera/cam_jpeg/jpeg_hw/jpeg_enc_hw/jpeg_enc_dev.o \
	camera/cam_jpeg/jpeg_hw/jpeg_enc_hw/jpeg_enc_core.o \
	camera/cam_jpeg/jpeg_hw/jpeg_enc_hw/jpeg_enc_soc.o \
	camera/cam_jpeg/jpeg_hw/jpeg_dma_hw/jpeg_dma_dev.o \
	camera/cam_jpeg/jpeg_hw/jpeg_dma_hw/jpeg_dma_core.o \
	camera/cam_jpeg/jpeg_hw/jpeg_dma_hw/jpeg_dma_soc.o \
	camera/cam_jpeg/jpeg_hw/cam_jpeg_hw_mgr.o \
	camera/cam_jpeg/cam_jpeg_dev.o \
	camera/cam_jpeg/cam_jpeg_context.o \
	camera/cam_fd/fd_hw_mgr/fd_hw/cam_fd_hw_dev.o \
	camera/cam_fd/fd_hw_mgr/fd_hw/cam_fd_hw_core.o \
	camera/cam_fd/fd_hw_mgr/fd_hw/cam_fd_hw_soc.o \
	camera/cam_fd/fd_hw_mgr/cam_fd_hw_mgr.o \
	camera/cam_fd/cam_fd_dev.o \
	camera/cam_fd/cam_fd_context.o \
	camera/cam_lrme/lrme_hw_mgr/lrme_hw/cam_lrme_hw_dev.o \
	camera/cam_lrme/lrme_hw_mgr/lrme_hw/cam_lrme_hw_core.o \
	camera/cam_lrme/lrme_hw_mgr/lrme_hw/cam_lrme_hw_soc.o \
	camera/cam_lrme/lrme_hw_mgr/cam_lrme_hw_mgr.o \
	camera/cam_lrme/cam_lrme_dev.o \
	camera/cam_lrme/cam_lrme_context.o
